### PR TITLE
startup script for systemd

### PR DESCRIPTION
**Pull request by cbueche**
Dear Simon,

here a very modest contribution, a startup script for CentOS (other systemd-based Linux could use it as well).

Regards,
Charles

### CODE REVIEW

**Comment by zzaflemi** [comment]
@cbueche thanks for the script.  I'm using it.  One minor suggestion.  Put the -S option (and maybe all options) before the -c config file.  I don't know why, but at least on my CentOS system if I don't put the -S option first then it does not actually do the source address spoofing.

**Comment by sleinen** [comment]
Dear Charles (@cbueche),

thanks for the contribution! And sorry for the late reply; I was asleep at the wheel.

This is becoming very useful as more and more systems adopt systemd.  I'll happily merge it, but I'd like you to address @zzaflemi's comment first.  For better or (probably) worse, samplicator's argument parsing is "stateful", so the `-S` option only affects destinations that follow it.  Therefore the `-S` should generally precede those destinations, whether they are specified via a conf file or directly on the command line.  Thanks!

**Comment by cbueche** [comment]
Hello Simon and Andy,

thanks for the feedback. I have fixed my script and reformatted the doc. Pull request is ready I think.

Regards,
Charles

**Comment by sleinen** [comment]
@cbueche: may I mention you as a contributor in the `AUTHORS` file?

**Comment by cbueche** [comment]
sure go ahead.
`Charles Bueche <bueche@netnea.com>`

**Pull request merged**
